org: x23176458
app: lambdas
service: ric-redis-operations

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  timeout: 30
  iam:
    role:
      statements:  # Default IAM role permissions for all functions
        - Effect: "Allow"
          Action:
            - "logs:*"
            - "lambda:GetLayerVersion"
          Resource: "*"

functions:
  redisTimeAdjustmentsForEndpoints:
    handler: ./redisTimeAdjustmentsForEndpoints.handler
    layers:
      - arn:aws:lambda:eu-west-1:557690584148:layer:dependencies-layer:13
    memorySize: 128
    timeout: 30
    events: []
    vpc:
      securityGroupIds:
        - sg-0307564d9956a71fa
      subnetIds:
        - subnet-04bdf4b9558e72dee
        - subnet-03adaef5d4afc6b48
    role: RedisFunctionRole  # Custom IAM role for this function

  queryCloudwatchAndUpdateFunctionTimes:
    handler: ./queryCloudwatchAndUpdateFunctionTimes.handler
    memorySize: 256 # Increase memory if required
    timeout: 900 # Maximum timeout of 15 minutes
    environment:
      REDIS_FUNCTION_NAME:
        Ref: RedisTimeAdjustmentsForEndpointsLambdaFunction
    # events:
    #   - schedule:
    #       rate: rate(15 minutes) # Runs every 15 minutes
    #       enabled: true # Ensures the rule is active
  keepLambdasWarm:
    handler: ./keepLambdasWarm.handler
    memorySize: 256 # Increase memory if required
    timeout: 900 # Maximum timeout of 15 minutes
    environment:
      CENTRALISED_LOG_GROUP_NAME: 'RIC-CRUD-log-group'
    # events:
    #   - schedule:
    #       rate: rate(15 minutes) # Runs every 15 minutes
    #       enabled: true # Ensures the rule is active

resources:
  Resources:
    RedisFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: redis-function-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: RedisAccessPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                  Resource:
                    - arn:aws:secretsmanager:us-east-1:557690584148:secret:ric-credentials-*
                - Effect: Allow
                  Action:
                    - elasticache:DescribeCacheClusters
                    - elasticache:DescribeReplicationGroups
                    - elasticache:DescribeCacheSubnetGroups
                    - elasticache:ListTagsForResource
                  Resource: "*"
